baseURL = 'https://gelzonexunsas.github.io/'
languageCode = 'en-us'
title = 'Gelzone Unsas'
theme = 'ananke'
publishDir = "docs"

[[params.ananke_socials]]
name = "Youtube"
url = "https://www.youtube.com/channel/UCs_AJP0KDnVPcPugtp6k37Q"

[[params.ananke_socials]]
name = "Github"
url = "https://github.com/GelzoneXUnsas"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[taxonomies]
   tag = "tags"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "Games"
url = "/tags/Games"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4