baseURL = 'https://gelzonexunsas.github.io/'
languageCode = 'en-us'
title = 'Gelzone Unsas'
theme = 'ananke'
publishDir = "docs"

[params]
  favicon = "images/profile/IMG_9741-modified.png"
  site_logo = "images/profile/IMG_9741-modified.png"
  font-awesome = true

[[params.ananke_socials]]
name = "Youtube"
url = "https://www.youtube.com/channel/UCs_AJP0KDnVPcPugtp6k37Q"

[[params.ananke_socials]]
name = "Github"
url = "https://github.com/GelzoneXUnsas"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
hasCJKLanguage = true
enableEmoji = true

[taxonomies]
   tag = "tags"

[[menu.main]]
name = "About"
url = "/about"
pre = "<i class='fa-solid fa-user'></i>"
weight = 1

[[menu.main]]
name = "Projects"
url = "/tags/projects"
pre = "<i class='fa-solid fa-folder'></i>"
weight = 2

[[menu.main]]
name = "Games"
url = "/tags/Games"
pre = "<i class='fa-solid fa-gamepad'></i>"
weight = 3

[[menu.main]]
name = "Music"
url = "/tags/Music"
pre = "<i class='fa-solid fa-guitar'></i>"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
pre = "<i class='fa-solid fa-paper-plane'></i>"
weight = 5
